# Generated by Django 5.0.4 on 2024-05-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalaciones', '0005_historico_dia_historico_hora_historico_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'ACTIVA'), ('S', 'SOLUCIONADA')], max_length=20)),
                ('tipo', models.CharField(choices=[('l', 'Leve'), ('i', 'Intermedia'), ('c', 'Crítica')], max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
    ]
