# Generated by Django 5.0.4 on 2024-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmas',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('SOLUCIONADA', 'SOLUCIONADA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='tipo',
            field=models.CharField(choices=[('LEVE', 'LEVE'), ('INTERMEDIA', 'INTERMEDIA'), ('CRÍTICA', 'CRÍTICA')], max_length=20),
        ),
    ]
