# Generated by Django 5.0.4 on 2024-05-16 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('cp', models.PositiveIntegerField()),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_inst', models.DateField()),
                ('modelo_inst', models.CharField(max_length=30)),
                ('fabricante_inst', models.CharField(max_length=30)),
                ('nserie_inst', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
