# Generated by Django 5.0.4 on 2024-05-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0002_instxusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstxUsuario',
        ),
    ]
