# Generated by Django 5.0.4 on 2024-05-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0003_delete_instxusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores_Actuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumida', models.DecimalField(decimal_places=1, max_digits=6)),
                ('generada', models.DecimalField(decimal_places=1, max_digits=6)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
    ]
