# Generated by Django 5.0.4 on 2024-05-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0004_valores_actuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('consumida', models.DecimalField(decimal_places=1, max_digits=6)),
                ('generada', models.DecimalField(decimal_places=1, max_digits=6)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
                ('consumida', models.DecimalField(decimal_places=1, max_digits=6)),
                ('generada', models.DecimalField(decimal_places=1, max_digits=6)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('consumida', models.DecimalField(decimal_places=1, max_digits=6)),
                ('generada', models.DecimalField(decimal_places=1, max_digits=6)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('consumida', models.DecimalField(decimal_places=1, max_digits=6)),
                ('generada', models.DecimalField(decimal_places=1, max_digits=6)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
    ]
