# Generated by Django 5.0.4 on 2024-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0005_historico_dia_historico_hora_historico_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico_dia',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='historico_dia',
            name='year',
        ),
        migrations.AlterField(
            model_name='historico_dia',
            name='dia',
            field=models.DateField(),
        ),
    ]
