# Generated by Django 5.0.4 on 2024-06-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0006_remove_historico_dia_mes_remove_historico_dia_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico_Year',
        ),
    ]
