# Generated by Django 5.0.6 on 2024-07-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0007_delete_historico_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalacion',
            old_name='fabricante_inst',
            new_name='fabricante_inv',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='modelo_inst',
            new_name='modelo_inv',
        ),
        migrations.RenameField(
            model_name='instalacion',
            old_name='nserie_inst',
            new_name='nserie_inv',
        ),
    ]
