# Generated by Django 5.0.4 on 2024-05-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=80)),
                ('empresa', models.CharField(default='', max_length=50)),
                ('cif', models.CharField(default='', max_length=10)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('cp', models.PositiveIntegerField()),
                ('poblacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
