# Generated by Django 5.0.4 on 2024-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='instalador',
            field=models.BooleanField(default=True),
        ),
    ]
