# Generated by Django 5.0.4 on 2024-05-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_userdata_cp_alter_userdata_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
