# Generated by Django 5.0.4 on 2024-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_userdata_cp_alter_userdata_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='instalador',
            field=models.IntegerField(default=0),
        ),
    ]
