# Generated by Django 5.0.4 on 2024-05-17 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0003_delete_instxusuario'),
        ('usuarios', '0006_alter_userdata_instalador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioxinst',
            unique_together={('user', 'inst')},
        ),
    ]
