# Generated by Django 5.0.4 on 2024-07-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarioxinst_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='aero',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='coch_elec',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
