# Generated by Django 5.0.4 on 2024-07-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_userdata_aero_userdata_coch_elec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='aero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='coch_elec',
            field=models.BooleanField(default=False),
        ),
    ]
