# Generated by Django 5.0.4 on 2024-07-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_userdata_aero_alter_userdata_coch_elec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='coch_elec',
            new_name='coche_elec',
        ),
    ]
